### ISSUE TITLE
Ability to edit any SVG files

### ISSUE THREAD

**Issue by kishorekumarxyz** [jensmtg/obsidian-diagrams-net#4]
Hello,

I love the fact that diagrams could quickly added to the notes using the plugin. But what is a bummer is the fact that you can't edit your SVG.

For example, I had https://en.wikipedia.org/wiki/Horizon#/media/File:Horizons.svg saved & embedded in my obsidian notes. When I right click and edit it says "Diagram is not valid (missing XML file)"

If only diagrams created with it can be opened and edited then it is limiting the possibilities to great extent. Can you please find a way to edit any SVG file?

**Comment by jensmtg** [comment]
Thanks for the feedback!

What you are requesting is a feature that must be solved in diagrams.net itself, not this integration plugin. 
Diagrams.net has a note about importing svg-files: https://www.diagrams.net/doc/faq/svg-insert
It describes how you can insert svg-files as scalable elements in diagrams, but also states:

> You cannot import an SVG representation of a diagram and edit it as a diagram. SVG does not save the connector information needed to be able to determine which elements are shapes and which are connectors.

The most relevant solution I can see to your problem would be to create a diagram, insert your svg-file, and make annotation on top of that. That doesn't let you edit the original svg, but at least combine it with your own drawing.
